### ISSUE TITLE
ASCII Falsifier with log.file

### ISSUE THREAD

**Issue by mMONTAGEe** [mMONTAGEe/College-Archive#9]
no idea honestly. it should work by principle to this

PC 1 - Runs the program, inputs character 'A' for example, Programs reveals falsified value and stores both.
PC 2 -  Runs the EXE, inputs falsified value and received the real one which was stored in EXE itself

**Comment by Gerardagh** [comment]
input data to program, it saves it into a text file and sends it over to a predefined email using a mailer then the program can decode the save file and reveal the true value over at the other device.

**Comment by mMONTAGEe** [comment]
without using any mail, the program should store the value somehow either as hidden text file or inside itself so that if i send it to someone else he could do the given decoding task

**Comment by Gerardagh** [comment]
cant do it within the program itself without using .NET window APP builders (usually C#), we'll have to do it via text file

**Comment by mMONTAGEe** [comment]
[Flowchart](https://cdn.discordapp.com/attachments/830857312280379442/1175490392502849588/image.png)

**Comment by mMONTAGEe** [comment]
commit #f035096
